Add gke specific changes for #384
prometheus/test-infra pull request #425
Opened 2020-08-06 20:16 UTC by weastel

Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>

2020-08-07 05:34 UTC, geekodour reviewed
Nice! This will make the #384 easier to follow. :)

Added a few small suggestions. Once this merged we must also make changes to the workflow files at : https://github.com/prometheus/prometheus/tree/master/.github/workflows

2020-08-07 05:34 UTC, geekodour commented on prombench/manifests/prombench/nodepools.yaml
> +projectid: {{ .GKE_PROJECT_ID }}
We want to move this file aswell to the new file name, no? don't forget to update the same in the Makefile :)

2020-08-07 05:34 UTC, geekodour commented on prombench/Makefile
>  	$(INFRA_CMD) gke nodepool check-running -a ${AUTH_FILE} \
I think you'd need to change `noodpool` to `node`? :thinking:

2020-08-07 05:34 UTC, geekodour commented on funcbench/manifests/cluster.yaml
> +projectid: {{ .GKE_PROJECT_ID }}
It'll be nice to update the filename for `cluster.yaml` for funcbench aswell :)

2020-08-07 05:37 UTC, geekodour commented
Another thing I would expect to be in this PR is the creation of docs directory and moving the GKE specific docs to `/docs/gke.md`, link to it from the prombench README. So the `/prometheus/README.md` will become significantly smaller.

2020-08-14 22:14 UTC, weastel commented on prombench/README.md
> +## Providers
@geekodour Can you please suggest me better heading and description for this.

2020-08-15 07:11 UTC, geekodour reviewed
Thanks for adding the changes and the description changes :) :sparkles: 

Added some suggestion, ~next thing to do with this PR is to update the commands in the funcbench Makefile as it also infra cli~.

2020-08-15 09:20 UTC, geekodour commented on prombench/Makefile
We should use the `PROVIDER` makefile variable for both funchbench and prombench Makefiles. ( Currently can be need in #384 Makefile for prombench)

2020-08-15 16:29 UTC, geekodour requested changes

2020-08-15 16:29 UTC, geekodour commented on .github/workflows/grafana_dashboard.yaml
>          AUTH_FILE: ${{ secrets.TEST_INFRA_GKE_AUTH }}
```suggestion
        AUTH_FILE: ${{ secrets.TEST_INFRA_PROVIDER_AUTH }}
```

2020-08-15 20:44 UTC, geekodour reviewed
small doc changes, I tested this. will merge once changes are addressed :)

2020-08-16 06:26 UTC, geekodour commented
@krasi-georgiev can you take a final look before merging? :)

2020-08-16 06:28 UTC, geekodour commented
@weastel you should make a PR to update the prometheus/prometheus github action workflow files aswell that will be affected by changes in this PR.

2020-08-19 07:20 UTC, merged

2020-08-19 07:21 UTC, geekodour commented
@krasi-georgiev I merged this as it was blocking few other PRs. Please still take a look at it, if we need to change anything back.

@weastel thanks for this! :)