Upgrading the GKE Version from 1.14 to 1.21
prometheus/test-infra pull request #558
Opened 2023-06-16 19:52 UTC by saketjajoo

Prombench uses GKE version 1.14 (which is end of life and end of support - https://cloud.google.com/kubernetes-engine/docs/release-schedule).

This commit upgrades the GKE version to 1.21. Although, 1.21 is also end of life and end of support, it is the latest and greatest version that can support prombench while not making major changes to the prombench code. This is because, 1.22 version onwards, the `v1beta` apis have been deprecated (which prombench uses).

2023-06-21 00:19 UTC, macxamin requested changes
Please rebase based on HEAD. so commit [Update GKE Node pool base image](https://github.com/prometheus/test-infra/pull/556/commits/6e2d90b43fdb2407d5c33fa9416e1cb5d36e3a96) doesn't show up as part of your PR.

2023-06-21 19:57 UTC, macxamin approved these changes
Good work!

2023-06-21 19:59 UTC, saketjajoo commented
c.c: @bwplotka - Can you please review and approve this PR?

2023-06-23 12:39 UTC, bwplotka approved these changes
Thank you! Great job! 

PS: Rebase is needed? 🤔

2023-06-23 15:06 UTC, saketjajoo commented
@bwplotka I've rebased this PR to be in sync with the master branch. Can you please review and merge this (I am not able to do so as I don't have the write access to the repo)?
Thank You!

2023-06-23 18:13 UTC, bwplotka approved these changes
Lgtm!

2023-06-23 18:13 UTC, merged