PR for #688 and #705
prometheus/test-infra pull request #725
Opened 2024-08-27 23:13 UTC by HarshitNagpal29

@SuperQ Sir for now i have commented out the part of .github which was mentioning load-generator directory because otherwise I was not able to stage my commits please have a look once.

2024-08-29 13:08 UTC, HarshitNagpal29 commented
@SuperQ Sir, can you please check it once?

2024-08-30 04:32 UTC, SuperQ requested changes

2024-08-30 04:32 UTC, SuperQ commented on tools/load-generator/Dockerfile
> +RUN go build -o load-generator .
We don't do builds in Docker here. What you want to do is add the new tool to the top level `.promu.yml`. Take a look at `tools/fake-webserver/Dockerfile` for an example.

2024-08-30 04:32 UTC, SuperQ commented on .github/dependabot.yml
> +  #- package-ecosystem: "pip"
Please remove rather than comment out.

2024-08-30 04:32 UTC, SuperQ commented on prombench/manifests/prombench/benchmark/6_loadgen.yaml
> +      - name: binary_arithmetic_operators
This change seems unrelated.

2024-08-30 04:32 UTC, SuperQ commented on tools/load-generator/main.go
> +	namespace = os.Args[1]
This appears unused.

2024-08-30 04:32 UTC, SuperQ commented
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

2024-08-30 04:36 UTC, SuperQ commented on prombench/manifests/prombench/benchmark/6_loadgen.yaml
> +      - name: binary_arithmetic_operators
Ahh, this is for #705

2024-08-30 05:56 UTC, HarshitNagpal29 commented
@SuperQ Sir first of all really sorry for not clarifying properly about PR, yes it resolved 2 issues this one and #705. I have a seperate PR for #705 as well but no was reviewing it.

Also the changes you suggested I will make in few hour and commit changes, and will see why tests are failing, and try to resolve it.

2024-08-30 05:59 UTC, SuperQ commented
We generally don't review if tests are failing.

2024-08-30 06:00 UTC, HarshitNagpal29 commented
Also sir can you look for issue #594 once, like I have proposed it's solution and not created PR, I have mentioned everything there once you can check I have ready solution in python I will create it in go aswell.

2024-08-30 15:57 UTC, HarshitNagpal29 commented
@SuperQ Sir i have made the changes as suggested by you, PTAl.

2024-08-30 15:58 UTC, HarshitNagpal29 commented
i dont know why DCO is failing even after git commit -s --amend

2024-08-31 04:08 UTC, SuperQ commented
Each individual commit must be signed off. You can use `git rebase -i origin/master` to squash your commits.

2024-09-03 02:58 UTC, HarshitNagpal29 commented
@SuperQ Hi Sir, hope you are doing well, I was having multiple issues even after rebasing so I have created a new PR https://github.com/prometheus/test-infra/pull/743 signing and it has passed DCO, please review and approve the changes.

2024-09-04 16:57 UTC, HarshitNagpal2901 commented
@SuperQ Sir can I close this PR? and you can merge another one, is it fine?

2024-09-21 15:28 UTC, SuperQ commented
Superseded by #748

2024-09-21 15:28 UTC, closed without merging